### ISSUE TITLE
Process grammar and non-grammar dictionary data

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#331]
### What needs to get done

Craft-application added support for processing grammar in the `organize` keyword but it cannot parse a mix of grammar and non-grammar data:

For example, when building for `arm64`, the following yaml:
```yaml
organize:
- on amd64 to amd64:
    hello-world.sh: hello-world-amd64.sh
- on amd64 to arm64:
    hello-world.sh: hello-world-arm64.sh
- test-file.in: test-file.out
```

should be processed to:
```yaml
organize:
  hello-world.sh: hello-world-arm64.sh
  test-file.in: test-file.out
```

### Why it needs to get done

To make grammar in the `organize` keyword useable.
