### ISSUE TITLE
spec for handling build-time secrets

### ISSUE THREAD

**Issue by tigarmo** [canonical/craft-application#50]
### What needs to get done

Create a spec + prototype for supporting build-time secrets in the applications. The idea is to follow [spread's lead](https://github.com/snapcore/spread#environments): For example, a declaration like:

```
parts:
    part1:
        source: https://user:$(HOST: GIT_PASS)@git.com
        source-type: git
        ....
```

will cause the application to evaluate the `GIT_PASS` environment variable on the host, replacing its value in the `source` line.

### Why it needs to get done

Users need a way to handle passwords, api keys, etc without recording them in the application's project files.
