### ISSUE TITLE
Use platform for build environment names

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#600]
### What needs to get done

Change the instance naming convention from:

```
<app>-<project>-on-<build-on>-for-<build-for>-<project-dir-inode>
```

to:
```
<app>-<project>-<platform>-<project-dir-inode>
```

### Why it needs to get done

To avoid the same instance getting used for different builds.

### Example
Currently, these use the same build environment:

```
platforms:
  noble:
      build-on: amd64
      build-for: amd64
  noble-debug:
      build-on: amd64
      build-for: amd64
```

This is also a problem for multi-base recipes (https://github.com/canonical/charmcraft/issues/2058).
