### ISSUE TITLE
Discrepancies between platforms processing and schemas

### ISSUE THREAD

**Issue by lengau** [canonical/craft-application#688]
### Bug Description

We have some edge cases where what platforms entries are valid in the application and what's valid in the schema are inconsistent due to preprocessing. More importantly, some valid values are not flagged in the schema

### To Reproduce

Each of the following valid entries should be validated as valid by the schema:

```yaml
platforms:
  amd64:
  all:
    build-on: [amd64]
  ppc64el:
    build-on: s390x
```

And each of the following invalid entries should behave the same in the schema as when starting an app.

```yaml
platforms:
  my-laptop:  # platform name is not a valid architecture, cannot be used in build-for
    build-on: [amd64]
```
