### ISSUE TITLE
Internal errors for `build-on: [all]`

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#690]
```yaml
name: testcraft
version: "0.1"

base: ubuntu@24.04
platforms:
  all:
    build-on: [all]
    build-for: [all]

parts:
  my-test:
    plugin: nil
```

```bash
craft-application/testcraft> python3 ./__main__.py pack
testcraft internal error: ValueError("'all' is not a valid DebianArchitecture")
```

It's not surprising for a user to attempt to use `all` in `build-on`.  Previously, Snapcraft would get to unmarshal the project and produce a user-friendly error like:
```
> snapcraft pack
Bad snapcraft.yaml content:
- 'all' cannot be used for 'build-on' (in field 'platforms')
```
