### ISSUE TITLE
internal errors for `all` platform

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#692]
### What needs to get done

```yaml
name: testcraft
version: "0.1"

base: ubuntu@24.04
platforms:
  all:

parts:
  my-test:
    plugin: nil
```

```bash
craft-application/testcraft> python3 ./__main__.py pack
testcraft internal error: 1 validation error for dict[literal['platforms'],dict[str,Platform]]
platforms.all
  Input should be a valid dictionary or instance of Platform [type=model_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/model_type
```

It's not surprising for a user to attempt to use `all` in `build-on`.  Previously, Snapcraft would get to unmarshal the project and produce a user-friendly error like:
```
> snapcraft pack
Bad snapcraft.yaml content:
- 'all' cannot be used for 'build-on' (in field 'platforms')
```

### Why it needs to get done

na
