### ISSUE TITLE
craft-platforms errors aren't caught

### ISSUE THREAD

**Issue by mr-cal** [canonical/craft-application#693]
### testcraft.yaml
```yaml
name: testcraft
version: "0.1"

base: ubuntu@24.04
platforms:
  a:
    build-on: [amd64]
    build-for: [all]
  b:
    build-on: [riscv64]
    build-for: [all]

parts:
  my-test:
    plugin: nil
```

### error
```bash
craft-application/testcraft> python3 __main__.py pack
testcraft internal error: AllSinglePlatformError(message='build-for: all requires exactly one platform definition (2 provided)', details='build-for: all defined in platforms: a,b', resolution="Provide only one platform with only build-for: all or remove 'all' from build-for options.", docs_url=None, doc_slug=None, logpath_report=True, reportable=True, retcode=1)
```

[full pastebin](https://paste.ubuntu.com/p/WHxprfk3Mb/)

### solution

I think that craft-application could either catch and re-raise craft-cli errors or add another `except` block for craft-platforms errors [here](https://github.com/canonical/craft-application/blob/5cf3d4071569e281cf06f07a119e45659d00d3fb/craft_application/application.py#L613).
