### ISSUE TITLE
Means to reduce duplication of plugin fields

### ISSUE THREAD

**Issue by sed-i** [canonical/craft-application#99]
### What needs to get done

It could be handy if a recurring repo could be mentioned only once, for example:

```yaml
definitions:  
  kubeflow-source: &kubeflow-source  
    source: https://github.com/kubeflow/kubeflow  
    source-type: git  
    source-tag: v1.7-branch  # upstream branch  
    source-depth: 1

parts:  
  backend:  
    plugin: nil  
    <<: *kubeflow-source
```

Currently this fails with:
```
Bad rockcraft.yaml content:
- extra field 'definitions' not permitted in top-level configuration
```

### Why it needs to get done

If the same repo+tag are used multiple times, it could be easier to maintain and easier to read.
